export const colors = {
  primary: '#006a64',
  primaryContainer: '#03c1b6',
  onPrimary: '#ffffff',
  secondary: '#565e74',
  secondaryContainer: '#dae2fd',
  background: '#f8f9ff',
  surface: '#f8f9ff',
  surfaceContainerLow: '#eff4ff',
  surfaceContainer: '#e5eeff',
  surfaceContainerHigh: '#dce9ff',
  surfaceContainerHighest: '#d3e4fe',
  surfaceContainerLowest: '#ffffff',
  onSurface: '#0b1c30',
  onSurfaceVariant: '#3c4948',
  outline: '#6c7a78',
  outlineVariant: '#bbcac7',
  error: '#ba1a1a',
  success: '#03c1b6', // mapped to primary container color for highlights
  text: '#0b1c30',
  textSecondary: '#565e74',
  card: '#ffffff',
  border: '#bbcac7',
};
